---
blank_issues_enabled: false
contact_links:
  - name: 💬 General Question
    url: https://github.com/jyunesmor/AppSaludProyectoFinal/discussions/categories/q-a
    about: Por favor, haga y responda preguntas como un hilo de discusión.